### ISSUE TITLE
Theme isn't look as it should

### ISSUE THREAD

**Issue by jobsamuel** [halfo/lambda-zsh-theme#1]
![screenshot](http://i.imgur.com/T3A1g0j.png)

I tested if I had unicode-compatible fonts using `echo "\ue0a0"`and it looks great.

What might be wrong with my terminal?

**Comment by alishihab** [comment]
With default fonts, not every unicode character will work. Try out these [compiled fonts.] (https://github.com/powerline/fonts)

**Comment by halfo** [comment]
With default fonts, not every unicode character will work. Try out [these compiled fonts.](https://github.com/powerline/fonts)

**Comment by halfo** [comment]
If changing your terminal font doesn't work, then you may try with different symbol (just replace that symbol in the file). By the way, I've already changed '⭠' with '' as the later one looks better with the theme. So, if you pull from the current head, it should work out of box. And thanks for the symbol!

**Comment by jobsamuel** [comment]
![screenshot](http://i.imgur.com/DoMleAS.png) 

OMG! It looks beautiful :heart_eyes:

Thanks a lot for your help and the update @halfo!

**Comment by halfo** [comment]
I'm really happy that you liked it :D
