### ISSUE TITLE
Right side on ubuntu

### ISSUE THREAD

**Issue by ghost** [halfo/lambda-zsh-theme#16]
I am on ubuntu and it looks like this. Right side of the terminal. It should display the hash code i suppose.
![screenshot from 2017-05-14 00-22-19](https://cloud.githubusercontent.com/assets/1254613/26029341/8595c888-383b-11e7-9668-84e5c323ca32.png)

**Comment by halfo** [comment]
Are you still facing this issue? If yes, can you share your OS version and the terminal you are using?

**Comment by ghost** [comment]
@halfo No, i don't use it.
