### ISSUE TITLE
git plugin is not displayed

### ISSUE THREAD

**Issue by dio4ev** [halfo/lambda-zsh-theme#17]
Hi!

I use this theme on my desktop and laptop, but the git plugin does not appear on my desktop. On my laptop everything works.

If I use another theme like powerlevel9k, then I have a working git plugin on the command line.

Does anybody know why this happens?

Regards,
Jonas

**Comment by dio4ev** [comment]
No solution? 
It's really annoying :/

**Comment by halfo** [comment]
Can you share your OS, version and the terminal you are using?

**Comment by dio4ev** [comment]
Sorry that's my fault......i thought i have already wrote it into my first comment ;-)

os:
> Linux Arch-Desktop 4.11.6-3-ARCH #1 SMP PREEMPT Thu Jun 22 12:21:46 CEST 2017 x86_64 GNU/Linux

shell:
> zsh 5.3.1

terminal:
> termite v12

wm:
> i3 version 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors

**Comment by halfo** [comment]
Can you try out https://github.com/halfo/lambda-mod-zsh-theme/pull/18 this to see if it solves your problem?

**Comment by dio4ev** [comment]
I will try this at the weekend
