### ISSUE TITLE
The 'Git' symbol is not normal

### ISSUE THREAD

**Issue by gmle** [halfo/lambda-zsh-theme#19]
Hello,developer,I used this theme in the process of finding a problem, Git symbols show garbled, how can this solution? My system is MacOS. Thanks.

**Comment by gmle** [comment]
The specific setting is “Format for git_prompt_info()”  “ZSH_THEME_GIT_PROMPT_PREFIX”

**Comment by Ma27** [comment]
would you mind showing us a screenshot which reveals the actual problem of this theme? :)

**Comment by gmle** [comment]
￼Yes, The location of the box is the wrong place, shown as garbled.
I guess because I do not have this symbol.
![error](https://user-images.githubusercontent.com/18096376/29164551-66d74af0-7df2-11e7-9d3f-6658367d1d41.png)

**Comment by Ma27** [comment]
do you have `font-awesome` installed?

**Comment by gmle** [comment]
No, I don't installed it, I have just looked at the **font-awesome** and installed the **font/FontAwesome.otf**, It's no change.  I don't know how to used it on **lambda-mod-zsh-theme**.   Can you tell me something?  Thanks.

**Comment by halfo** [comment]
I didn't use `font-awesome`, so can't help you issues with that. @Ma27 is more knowledgeable here.

You can try out other fonts (for example, fonts mentioned [here](https://github.com/halfo/lambda-mod-zsh-theme/issues/1)).

**Comment by Ma27** [comment]
@halfo well, after installing `font-awesome` globally the branch icon was shown properly, so I assume it might be a fix for this sort of issue

@gmle I'm unfortunately not a MacOS user, but each system installs its fonts somewhere to be used by userland applications. This support thread from the apple forum might help you with that: https://discussions.apple.com/thread/4944214?tstart=0

**Comment by gmle** [comment]
@Ma27 Thanks, I installed **font-awesome** fonts , but not solved this problem. I try to use other ways to solve it. And after resolving you will be restored
