### ISSUE TITLE
What's your terminal emulator?

### ISSUE THREAD

**Issue by EduardoRT** [halfo/lambda-zsh-theme#2]
Hi! I love your theme but I'm using iTerm2 as my terminal emulator and it doesn't look half as nice as yours, what are you using?

**Comment by halfo** [comment]
This is Ubuntu's default terminal (gnome terminal). I'm using a darker version of Paraiso theme. For iTerm2, check [this](https://github.com/idleberg/Paraiso-iTerm2) out.

**Comment by EduardoRT** [comment]
@halfo Nice! thank you very much!
