### ISSUE TITLE
Facing an issue when installing the theme

### ISSUE THREAD

**Issue by ratul0** [halfo/lambda-zsh-theme#20]
/Users/rat/.oh-my-zsh/themes/lambda-mod.zsh-theme:8: parse error near `\n'

Is this mean anything?

**Comment by halfo** [comment]
I'm not sure. Which OS are you using?

**Comment by ghost** [comment]
looks like you maybe didnt downloaded the raw file but the complete .html file and copied it over to the zsh theme directory?
Also did one time when I started using zsh themes

**Comment by anthonybrown** [comment]
How do I install the theme?
I tried to add it to my .zshrc file but that didn't work.

**Comment by anthonybrown** [comment]
nvm, I figured it out lol.

**Comment by AngryR4v3n** [comment]
> nvm, I figured it out lol.

@anthonybrown Can you explain how? Newbie here.

**Comment by halfo** [comment]
@molinajimenez  Please have a look at the [documentation](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes).
