### ISSUE TITLE
color preset

### ISSUE THREAD

**Issue by pr0grammr** [halfo/lambda-zsh-theme#24]
Can you post your color preset as shown in the screenshot?

**Comment by eroluysal** [comment]
+1

**Comment by Ma27** [comment]
Not sure if that helps anyone, but mine looks actually pretty similar.

I currently use `lambda-mod` on a terminal with kitty 0.13.3 and the following customizations:

```
font_family      FiraCode-Regular
bold_font        FiraCode-Bold
italic_font      auto
bold_italic_font auto
cursor_shape     beam
background       #222222

color1  #d17b49
color9  #d17b49
color4  #1e90ff
color12 #1e90ff
color5  #775759
color13 #775759
```

In the end the terminal looks like this:

![kitty with lambda-mod](https://i.imgur.com/8kIEdOY.jpg)

**Comment by halfo** [comment]
You may also like to follow this [comment](https://github.com/halfo/lambda-mod-zsh-theme/issues/4#issuecomment-193269680).
