### ISSUE TITLE
No Lambda Icon

### ISSUE THREAD

**Issue by gregorskii** [halfo/lambda-zsh-theme#5]
Hi there,

For some reason... I do not see the lambda icon. I do with the default ZSH lambda theme..

<img width="205" alt="screenshot 2016-03-31 10 27 33" src="https://cloud.githubusercontent.com/assets/1130448/14184692/36b3a2dc-f72b-11e5-9d15-6773255b2852.png">

Using antigen, iterm3 beta: iTerm2 2.9.20160313, Hack Font.

**Comment by halfo** [comment]
Hi! Well, I'm really clueless here. Try pasting `λ` in the terminal and see what happens. You may try changing the font too. I know it works on iTerm2 but don't know about iTerm3 beta.

**Comment by gregorskii** [comment]
That works.. :/

<img width="244" alt="screenshot 2016-04-01 10 56 18" src="https://cloud.githubusercontent.com/assets/1130448/14215535/6c15fa74-f7f8-11e5-9261-9b4b5a8e7d38.png">

**Comment by gregorskii** [comment]
Don't know why.. given the context but removing local on https://github.com/halfo/lambda-mod-zsh-theme/blob/master/lambda-mod.zsh-theme#L3 makes it work for me.

I am using Antigen to load it... maybe that has something to do with it?

**Comment by halfo** [comment]
I haven't tested with Antigen. I need to squeeze out some time to test it. Also, the codebase deserves a refactoring. Anyway, thanks for finding out a workaround. Lets keep this issue open until a suitable solution is found. Cheers!

**Comment by fcrespo82** [comment]
I have this same issue, the workaround by @gregorskii worked for me too.

I'm using zsh with zplug!

versions:
- zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
- zplug 2.3.4

**Comment by halfo** [comment]
I've seen people facing similar problem with __local__ in iterm3, but not in gnome-terminal. That's a bit weird. Thanks for letting us know.

**Comment by halfo** [comment]
Hi @gregorskii and @fcrespo82, are you guys still using this theme? Can I get a bit of help to solve this issue? Can you let me know if the patch mentioned here #10 solve's the issue or not?

**Comment by gregorskii** [comment]
I could test this, but I don't quite know how to pull the PR into Antigen.

I tried this:

```
antigen bundle halfo/lambda-mod-zsh-theme#10

antigen theme halfo/lambda-mod-zsh-theme lambda-mod
```

But it did not work, results in a bad URL:

```
Cloning into '.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-halfo-SLASH-lambda-mod-zsh-theme#10.git'...
fatal: https://github.com/halfo/lambda-mod-zsh-theme#10.git/info/refs not valid: is this a git repository?
ls: .antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-halfo-SLASH-lambda-mod-zsh-theme#10.git/: No such file or directory
ls: .antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-halfo-SLASH-lambda-mod-zsh-theme#10.git/: No such file or directory
ls: .antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-halfo-SLASH-lambda-mod-zsh-theme#10.git/: No such file or directory
```

Any ideas?

If #10 works I can pull from the new version and see if it fixes my issue as well.

**Comment by halfo** [comment]
I've created a [hot-fix](https://github.com/halfo/lambda-mod-zsh-theme/tree/hot-fix) branch from that pull request. Would that help?

**Comment by fcrespo82** [comment]
@halfo Sorry for the delay, it worked for me. I switched the it repo for the hot-fix branch and the lambda icon displayed correctly.

**Comment by halfo** [comment]
Awesome!! Thanks to @fcrespo82 and @gregorskii for the support. I'm closing the issue :)

**Comment by Ma27** [comment]
@halfo well, since this change the interface seems to be broken:

```
λ ma27 [~/Projects/nixos-config] →                                                                                                                                                                                                                                     [f58dd9a]
```

When you have a look at most of the oh-my-zsh themes (https://github.com/robbyrussell/oh-my-zsh/tree/master/themes) you'll see that they're using single quotes for the prompts (however I'm no ZSH expert, so I might be wrong with this assumption)

EDIT: I reverted to the old revision (2015-12-15) and it works fine again. Is there any possibility that the change breaks under certain circumstances?

**Comment by Ma27** [comment]
ping @halfo

**Comment by halfo** [comment]
@Ma27 Sorry for this really really late reply. This thing is broken again! The fix was working for me too. But now, it is not. I have to revert the changes and open this issue again. If any kind soul knows any solution, please reply.

**Comment by Ma27** [comment]
@halfo thanks for your reply,

I'm absolutely fine with reverting the commit (as this should fix it for me). However when you need someone to test or investigate when working on that issue, feel free to ping me as I really love this theme and I'm happy to help :-)

**Comment by sei40kr** [comment]
I'm using zplug and I've made it works fine.
https://github.com/sei40kr/lambda-mod-zsh-theme

I guess that zplug loads themes on child process, so we need to export a variable `LAMBDA`, or embed it into `PROMPT`.

**Comment by Ma27** [comment]
I think we can close this after the last patch
