### ISSUE TITLE
No git branch icon

### ISSUE THREAD

**Issue by Bluelich** [halfo/lambda-zsh-theme#7]
I had set it like this:
ZSH_THEME="lambda-mod"
but the icon for git-branch doesn't appear.
How can I do to make it works?

Thank you!

**Comment by cori** [comment]
You'll need to install a font that has the proper glyph for the branch icon. I use http://sourcefoundry.org/hack/.

**Comment by Bluelich** [comment]
@cori  Thank you!
I'd download the font from 
https://github.com/chrissimpkins/Hack#user-content-quick-installation.
(https://github.com/chrissimpkins/Hack/releases/download/v2.020/Hack-v2_020-ttf.zip)
And I'd set the font to hack in iterm2,but it doesn't works!

**Comment by Bluelich** [comment]
@cori  sorry!
I did it wrong!
Now I'd set the Non-ASCII Font to Hack,it works!
Thank you very much! 
Thank you!
